# Generated by Django 3.1.2 on 2020-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0002_auto_20201115_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_1', models.ImageField(blank=True, upload_to='slider/')),
                ('slider_1_info', models.TextField(blank=True)),
                ('slider_2', models.ImageField(blank=True, upload_to='slider/')),
                ('slider_2_info', models.TextField(blank=True)),
                ('slider_3', models.ImageField(blank=True, upload_to='slider/')),
                ('slider_3_info', models.TextField(blank=True)),
            ],
        ),
    ]
