# Generated by Django 3.1.2 on 2020-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='ProductManagement.Review'),
        ),
    ]
