# Generated by Django 3.1.2 on 2020-11-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0004_auto_20201120_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Username',
            new_name='user',
        ),
    ]
