# Generated by Django 3.1.2 on 2020-11-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='User_name',
        ),
    ]
