# Generated by Django 3.1.2 on 2020-11-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20201114_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User_name',
            new_name='Username',
        ),
    ]
