# Generated by Django 3.1.2 on 2020-11-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_auto_20201125_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='user',
        ),
    ]
